services:
  mongo:
    build: .
    image: mongo-rs
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    healthcheck:
      test: >
        echo "try {
          rs.status()
        } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [{_id: 0, host: 'host.docker.internal:27017'}]
          })
        }" | mongosh --port 27017 --username admin --password secret --authenticationDatabase admin --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "./mongo_data:/data/db"
      - "./custom-entrypoint.sh:/custom-entrypoint.sh"
